---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(googlesheets4)
library(ggrepel)
library(ggthemes)
library(ggthemr)
```

```{r}
url_escaleta <- "https://docs.google.com/spreadsheets/d/1ihrKLlfM3YidL0RlhlNGN3ZdLXArdR_o8ABX8Orw_2s/edit?usp=sharing"
gs_id <- as_sheets_id(url_escaleta)
```

```{r}
df_escaleta <- read_sheet(gs_id,"v1")
```

```{r}
df_escaleta %>% count(`Ano da Cena`)
```

```{r}
df_escaleta %>% count(`Abrev Cena`)
```


```{r}
df_escaleta %>%
  ggplot(aes(x=`Ano da Cena`)) +
  geom_histogram(stat="count") +
  coord_flip()
```

```{r}
df_ren <- df_escaleta %>%
  rename(ano=`Ano da Cena`,
         cena=`Numero da Cena`,
         abrev=`Abrev Cena`,
         nome=`Nome da Cena`) %>%
  arrange(cena)

kap <- df_ren%>%filter(abrev%>%str_detect("Kaparot|Festa 2|Faca 3|Vernissage|Rabina"))%>%pull(cena)

main_line <- 2010:2050
df_out <- df_ren %>% filter(!(ano%in%main_line))
df_main <- df_ren %>% filter(ano%in%main_line) %>%
  mutate(hjust=if_else(cena%in%kap,"right","left"),
         nudge_y=if_else(cena%in%kap,-1,1.5))
df_kap <- df_ren %>% filter(ano%in%main_line,cena>=kap)
# %>% mutate(hjust=if_else(cena%in%right_just,"right","left"))

ggthemr('solarized', type = 'outer')
df_ren %>%
  ggplot(aes(x=cena,y=ano)) +
  geom_step(color="gray") +
  geom_point() +
  geom_text(aes(x=cena,y=nudge_y+ano,label=abrev,hjust=hjust),
            angle=45,size=2.5,
            inherit.aes=F,
            data=df_main) +
  geom_text_repel(aes(x=cena,y=ano,label=sprintf("%s (%d)",abrev,ano)),size=2.5,
                  hjust="left",inherit.aes=F,
                  data=df_out) +
  #geom_text_repel(aes(x=cena,y=ano,label=abrev),size=2.5,angle=45,inherit.aes=F,
   #               box.padding=0,force=.25,direction="y",nudge_y=-.1,
    #              data=df_kap) +
  coord_fixed(ratio=.33
              ,ylim=c(min(df_ren$ano),2040)
              ,xlim=c(1,nrow(df_ren)+2)
              ) +
  scale_y_continuous(breaks=seq(1900,2040,10)) +
  scale_x_continuous(breaks=c(1,seq(5,max(df_ren$cena),5))) +
  theme(axis.text.y = element_text(angle = 0, hjust = 1)) # + theme(plot.background = element_rect(fill = "black"))
```


```{r}
ggsave("faca.png",width=16,height=8)
```


```{r}
library(igraph)
```

https://www.jessesadler.com/post/network-analysis-with-r/

```{r}
routes_igraph <- graph_from_data_frame(d = edges, vertices = nodes, directed = TRUE)
```


```{r}
routes_igraph %>%
  ggraph(layout = "linear") + 
  geom_edge_arc(aes(width = weight), alpha = 0.8) + 
  scale_edge_width(range = c(0.2, 2)) +
  geom_node_text(aes(label = label)) +
  labs(edge_width = "Letters") +
  theme_graph()
```
